package imageProc;
/**
 * 
 * @author Jay
 *
 */
public enum ProcOptions {
	DETECT_FACE,
	DETECT_MULTIPLE_FACES,
	TRACK_FACE,
	TRACK_MULTIPLE_FACES,
	TRACT_MOUSE_WITH_FACE,
	ENABLE_HAND_GESTURES,
	MULTIPLE_OBJECT_MODE,
	SINGLE_OBJECT_MODE,
	TRACK_MOUSE_WITH_OBJECT,
	
	ALERT_TRACKED_OBJECTS_COUNT,
	ALERT_TRACKED_OBJECT_LOST,
	ALERT_TRACKING_NEW_OBJECT,
	ALERT_NO_TRACKED_OBJECTS,
}
